version: 2.1
jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["f9:f1:fc:68:82:47:28:92:4c:70:86:cd:ef:e6:1e:4a"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: add ssh key to known hosts
          command: |
            echo '3.230.170.49 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNughFoLItDS3PXP1MPZL9Jx3C6ATn0AUET6WVMm6cd' >> ~/.ssh/known_hosts
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
