version: 2.1
jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ab:4e:bb:20:3a:88:4e:4f:6a:0d:f7:24:07:3d:ed:9d"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml -vvv -i inventory

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
